Add test utilities, refactor
smartcontractkit/ea-framework-js pull request #74
Opened 2023-02-21 04:59 UTC by alejoberardino

This is quite a loaded PR. Changes:
- Change default background execute sleep from 1ms to 10ms
- Add stacktrace logging on background execute errors
- Add transport name and endpoint to logs written in a background execute context
- Separate port listening on the rest APIs to a separate function `expose` to maintain backwards compat, while leaving a `start` function to build the APIs and start background executes as necessary
- Make HTTP transport sleep upon hitting a requester queue overflow
- Add more logging for provider errors in HTTP transport
- Add 1s time to wait since a WS connection was opened to avoid problems like messages never being sent
- Add check to send messages only if the WS connection is open
- Add TestAdapter utility class, to start an adapter and provide methods for common patterns (sending a request to the EA, sending one + waiting for bg execute + sending again for result, getting metrics, etc.)
- Refactor and clean up _all_ test suites

2023-02-22 11:01 UTC, boxhock requested changes

2023-02-22 18:28 UTC, alejoberardino commented on src/index.ts
> +  await exposeApp(metricsApi, metricsUrl, adapter.config.METRICS_PORT)
It is not, will fix

2023-02-22 18:30 UTC, alejoberardino commented on src/transports/http.ts
> +        logger.info(errorMessage)
I think warns should mean there's something the NOP should be consciously aware of, and that they could potentially take action on. In this case if the provider starts failing I think it's fine if they peek through the logs and see issues, but there's nothing they can do so it's not on them to do something. Does this make sense?

2023-02-22 18:32 UTC, alejoberardino commented on src/transports/websocket.ts
> +      }
It's intended to be there, to avoid the case where we open and close connections immediately, to avoid potential issues in very fast adapters

2023-02-23 16:56 UTC, boxhock commented on src/transports/http.ts
> +        logger.info(errorMessage)
Yes, that does make sense, but

> something the NOP should be consciously aware of, and that they could potentially take action on

I feel like this does describe erroring requests to the data provider though:

- NOPs should be aware that the EA is not getting data from the DP exactly as expected
- NOPs could potentially take action if they run out of DP API credits, they are requesting data they don't have access to with their API plan, etc.

I think the question of which log level to use for these logs is very even between info and warn, so unless the above convinces you then let's continue with info level (and potentially talk to NOPs to get their opinion in the future).

2023-02-23 18:35 UTC, boxhock approved these changes

2023-02-23 18:37 UTC, boxhock commented on src/transports/http.ts
> +        logger.info(errorMessage)
Have added it to the next meeting notes :+1:

2023-02-23 20:08 UTC, merged